#!/bin/sh

docker run --rm \
--name electrs \
--env-file=.env \
-e ELECTRS_DB_DIR=${DB_DIR} \
-e ELECTRS_DAEMON_DIR=${DAEMON_DIR} \
-e ELECTRS_NETWORK=bitcoin \
-e ELECTRS_LOG_FILTERS=INFO \
-e ELECTRS_SERVER_BANNER="${BANNER}" \
-e ELECTRS_DAEMON_RPC_ADDR=${BTC_ADDR}:${BTC_RPC_PORT} \
-e ELECTRS_DAEMON_P2P_ADDR=${BTC_ADDR}:${BTC_P2P_PORT} \
-e ELECTRS_ELECTRUM_RPC_ADDR=${HOST_ADDR}:${HOST_PORT} \
-v ${HOST_BITCOIN_DIR}:${DAEMON_DIR}:ro \
-v ${HOST_ELECTRS_DIR}:/data \
-p ${HOST_PORT}:50001 \
${DOCKER_USER}/electrs:${TAG}
